[window]
padding = {x = 2, y = 2}

[colors]
primary.foreground = '#d8dee9' 
primary.background = '#1b2b34'
cursor.text = '#d8dee9' 
cursor.cursor = '#ec5f67' 

[font]
normal.family = 'Iosevka'
bold.family = 'Iosevka'
italic.family = 'Iosevka'
size = 16.0
