require('lsp.lua')
require('lsp.golang')
require('lsp.typescript')
require('lsp.ruby')
vim.api.nvim_command('augroup jdtls_lsp')
vim.api.nvim_command('autocmd!')
vim.api.nvim_command("autocmd FileType java lua require('lsp.java').setup()")
vim.api.nvim_command('augroup end')
